import Image from 'next/image'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'

const Layout = ({ children }) => (
  <div>
    <Head>
      <title>Ecohouse</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className='max-w-2xl mx-auto p-4 space-y-4'>
      {children}
    </main>
  </div>
)

export default Layout